package io.astrolabe.atlas

import io.astrolabe.fixtures.Fixture
import io.astrolabe.fixtures.FixtureRepos
import io.astrolabe.fixtures.TempRepo
import io.astrolabe.id.WorkspaceId
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertNull
import kotlin.test.assertTrue

/** P3.2.1: the runtime import graph produced into the P3.2.7 kernel types (§7.3). */
class ImportGraphTest {
    private val workspace = WorkspaceId("main")

    private fun graphOf(root: java.nio.file.Path) = ImportGraph.of(Atlas.build(root), workspace)

    private fun edges(graph: ImportGraph): Set<Pair<String, String>> =
        graph.graph.imports.mapTo(HashSet()) { it.importer.path to it.dependency.path }

    @Test
    fun `python rows become kernel files with resolved edges, one root package and lexical tier`() {
        FixtureRepos.materialize(Fixture.PythonSmall).use { repo ->
            val graph = graphOf(repo.root)
            val root = repo.root.fileName.toString()
            assertEquals(FixtureRepos.files(Fixture.PythonSmall).toSet(), graph.graph.files.mapTo(HashSet()) { it.path })
            assertEquals(root, graph.packageOf("pay/router.py"))
            assertEquals(ImpactScope(workspace, root), graph.file("tests/test_router.py").scope)
            assertEquals(setOf(ImpactScope(workspace, root)), graph.graph.coverage)
            assertEquals(IndexTier.Lexical, graph.graph.tier)
            val edges = edges(graph)
            assertTrue("pay/router.py" to "pay/handlers/user.py" in edges)
            assertTrue("tests/test_router.py" to "pay/router.py" in edges)
            assertTrue("pay/router.py" to "pyproject.toml" in edges, "a file imports its package manifest")
            assertTrue(graph.isComplete("pay/router.py"))
            assertTrue(graph.isComplete("tests/test_router.py"), "pytest is clearly external")
            assertTrue(graph.graph.complete)
            assertEquals(
                setOf("pay/router.py", "tests/test_handlers.py"),
                graph.importers("pay/handlers/user.py").mapTo(HashSet()) { it.path },
            )
        }
    }

    @Test
    fun `runtime-only python dependency marks its file incomplete and the analysis widens to the package FX37`() {
        TempRepo.create().use { repo ->
            repo.write("pyproject.toml", "[project]\nname = \"pay\"\n")
            repo.write("pay/__init__.py", "")
            repo.write("pay/core.py", "def core():\n    return 1\n")
            repo.write("pay/plugins.py", "import importlib\n\n\ndef load(name):\n    return importlib.import_module(name)\n")
            repo.write("tests/test_core.py", "from pay.core import core\n\n\ndef test_core():\n    assert core() == 1\n")
            repo.commit("initial")
            val graph = graphOf(repo.root)
            val root = repo.root.fileName.toString()

            assertFalse(graph.isComplete("pay/plugins.py"))
            assertTrue(graph.isComplete("pay/core.py"))
            assertFalse(graph.graph.complete)
            val reason = graph.unresolved("pay/plugins.py").single()
            assertTrue(reason.startsWith("dynamic import at line 5: importlib.import_module"), reason)
            assertEquals(setOf(ImpactDependency(graph.file("pay/plugins.py"), reason)), graph.graph.unresolved)

            val request = ImpactRequest(graph.graph, setOf(graph.file("pay/core.py")), emptyList(), emptyList(), emptyList(), true)
            val analysis = Impact.analyze(request)
            assertFalse(analysis.blastComplete)
            assertTrue(ImpactScope(workspace, root) in analysis.verificationScopes)
            assertTrue(analysis.issues.any { "pay/plugins.py" in it && "dynamic import" in it })
        }
    }

    @Test
    fun `reflection, dynamic script imports and generated markers are incomplete while static imports resolve`() {
        TempRepo.create().use { repo ->
            repo.write("build.gradle.kts", "plugins { java }\n")
            repo.write("src/main/java/app/Loader.java", "package app;\n\npublic class Loader {\n    Object load(String n) throws Exception {\n        return Class.forName(n).getDeclaredConstructor().newInstance();\n    }\n}\n")
            repo.write("src/main/java/app/Main.java", "package app;\n\nimport java.util.List;\nimport app.Loader;\n\npublic class Main {}\n")
            repo.write("web/package.json", "{ \"name\": \"web\" }\n")
            repo.write("web/src/lazy.ts", "export async function lazy(name: string) {\n  return import(name);\n}\n")
            repo.write("web/src/plain.js", "const fs = require(\"fs\");\nconst dyn = require(process.env.MOD);\nmodule.exports = { fs, dyn };\n")
            repo.write("web/src/client.ts", "// Code generated by openapi. DO NOT EDIT.\nexport const client = 1;\n")
            repo.write("web/src/index.ts", "import { lazy } from \"./lazy.ts\";\nimport { client } from \"./client.ts\";\nimport { missing } from \"./missing.ts\";\nexport { lazy, client, missing };\n")
            repo.commit("initial")
            val graph = graphOf(repo.root)

            assertFalse(graph.isComplete("src/main/java/app/Loader.java"))
            assertTrue(graph.unresolved("src/main/java/app/Loader.java").single().startsWith("reflection at line 5: Class.forName"))
            assertTrue(graph.isComplete("src/main/java/app/Main.java"), "java.util is clearly external")
            assertTrue("src/main/java/app/Main.java" to "src/main/java/app/Loader.java" in edges(graph))

            assertEquals(listOf("dynamic import at line 2: import"), graph.unresolved("web/src/lazy.ts"))
            assertEquals(listOf("dynamic import at line 2: require"), graph.unresolved("web/src/plain.js"))
            assertTrue(graph.unresolved("web/src/client.ts").single().startsWith("generated file:"))
            assertEquals(listOf("unresolved import ./missing.ts"), graph.unresolved("web/src/index.ts"))
            assertTrue("web/src/index.ts" to "web/src/lazy.ts" in edges(graph))
            assertEquals("web", graph.packageOf("web/src/index.ts"))
            assertEquals(repo.root.fileName.toString(), graph.packageOf("src/main/java/app/Main.java"))
        }
    }

    @Test
    fun `gradle and maven module dependencies join manifests and files import their own manifests`() {
        TempRepo.create().use { repo ->
            repo.write("settings.gradle.kts", "rootProject.name = \"mono\"\ninclude(\":core\", \":app\")\n")
            repo.write("core/build.gradle.kts", "plugins { kotlin(\"jvm\") }\n")
            repo.write("app/build.gradle.kts", "plugins { kotlin(\"jvm\") }\ndependencies {\n    implementation(project(\":core\"))\n}\n")
            repo.write("core/src/main/kotlin/core/Lib.kt", "package core\n\npublic fun lib(): Int = 1\n")
            repo.write("app/src/main/kotlin/app/Main.kt", "package app\n\nimport core.lib\n\npublic fun main(): Int = lib()\n")
            repo.write("mvn/pom.xml", "<project>\n  <artifactId>parent</artifactId>\n  <modules>\n    <module>lib</module>\n    <module>svc</module>\n  </modules>\n</project>\n")
            repo.write("mvn/lib/pom.xml", "<project>\n  <parent>\n    <artifactId>parent</artifactId>\n  </parent>\n  <artifactId>lib</artifactId>\n</project>\n")
            repo.write("mvn/svc/pom.xml", "<project>\n  <parent>\n    <artifactId>parent</artifactId>\n  </parent>\n  <artifactId>svc</artifactId>\n  <dependencies>\n    <dependency>\n      <groupId>x</groupId>\n      <artifactId>lib</artifactId>\n    </dependency>\n    <dependency>\n      <artifactId>junit</artifactId>\n    </dependency>\n  </dependencies>\n</project>\n")
            repo.commit("initial")
            val graph = graphOf(repo.root)
            val edges = edges(graph)

            assertEquals("core", graph.packageOf("core/src/main/kotlin/core/Lib.kt"))
            assertEquals("app", graph.packageOf("app/src/main/kotlin/app/Main.kt"))
            assertEquals("mvn/svc", graph.packageOf("mvn/svc/pom.xml"))
            assertTrue("app/build.gradle.kts" to "core/build.gradle.kts" in edges)
            assertTrue("settings.gradle.kts" to "core/build.gradle.kts" in edges)
            assertTrue("settings.gradle.kts" to "app/build.gradle.kts" in edges)
            assertTrue("app/src/main/kotlin/app/Main.kt" to "core/src/main/kotlin/core/Lib.kt" in edges)
            assertTrue("app/src/main/kotlin/app/Main.kt" to "app/build.gradle.kts" in edges)
            assertTrue("mvn/pom.xml" to "mvn/lib/pom.xml" in edges)
            assertTrue("mvn/svc/pom.xml" to "mvn/lib/pom.xml" in edges)
            assertFalse(edges.any { it.first == "mvn/svc/pom.xml" && it.second == "mvn/svc/pom.xml" })
            assertTrue(graph.graph.complete)

            // Editing core's build script blasts through core and into app via the kernel's reverse BFS.
            val analysis = Impact.analyze(ImpactRequest(graph.graph, setOf(graph.file("core/build.gradle.kts")), emptyList(), emptyList(), emptyList(), true))
            assertTrue(graph.file("core/src/main/kotlin/core/Lib.kt") in analysis.blast)
            assertTrue(graph.file("app/src/main/kotlin/app/Main.kt") in analysis.blast)
        }
    }

    @Test
    fun `monorepo packages resolve python and workspace script imports per package`() {
        TempRepo.create().use { repo ->
            repo.write("services/a/pyproject.toml", "[project]\nname = \"a\"\n")
            repo.write("services/a/pay/__init__.py", "")
            repo.write("services/a/pay/x.py", "def f():\n    return 1\n")
            repo.write("services/a/main.py", "from pay.x import f\nimport requests\n")
            repo.write("services/b/pyproject.toml", "[project]\nname = \"b\"\n")
            repo.write("services/b/main.py", "from pay.missing import z\n")
            repo.write("packages/ui/package.json", "{ \"name\": \"@acme/ui\" }\n")
            repo.write("packages/ui/src/index.ts", "export const ui = 1;\n")
            repo.write("packages/app/package.json", "{ \"name\": \"@acme/app\" }\n")
            repo.write("packages/app/src/index.ts", "import { ui } from \"@acme/ui\";\nimport react from \"react\";\nexport { ui, react };\n")
            repo.write("loose.py", "import os\n")
            repo.commit("initial")
            val graph = graphOf(repo.root)
            val edges = edges(graph)

            assertEquals("services/a", graph.packageOf("services/a/main.py"))
            assertTrue("services/a/main.py" to "services/a/pay/x.py" in edges)
            assertTrue(graph.isComplete("services/a/main.py"), "requests is clearly external")
            assertEquals(listOf("unresolved import pay.missing"), graph.unresolved("services/b/main.py"))
            assertTrue("packages/app/src/index.ts" to "packages/ui/src/index.ts" in edges)
            assertTrue(graph.isComplete("packages/app/src/index.ts"), "react is clearly external")
            assertNull(graph.packageOf("loose.py"), "no manifest covers the root")
            assertEquals(ImpactScope(workspace, null), graph.file("loose.py").scope)
            assertEquals(
                setOf("services/a", "services/b", "packages/ui", "packages/app"),
                graph.graph.coverage.mapNotNullTo(HashSet<String>()) { it.packageId },
            )
        }
    }

    @Test
    fun `tests_for joins atlas edges and naming conventions across the fixture languages`() {
        FixtureRepos.materialize(Fixture.PythonSmall).use { repo ->
            val graph = graphOf(repo.root)
            assertEquals(setOf("tests/test_router.py"), graph.testsFor(listOf("pay/router.py")).mapTo(HashSet()) { it.path })
            assertEquals(setOf("tests/test_handlers.py"), graph.testsFor(listOf("pay/handlers/user.py")).mapTo(HashSet()) { it.path })
            assertTrue(graph.testsFor(listOf("pyproject.toml")).isEmpty())
        }
        FixtureRepos.materialize(Fixture.GradleSmall).use { repo ->
            val graph = graphOf(repo.root)
            // HandlerTest imports pay.Request/Response, so the atlas edge joins it to Router.kt as well.
            assertEquals(
                setOf("src/test/kotlin/pay/RouterTest.kt", "src/test/kotlin/pay/handlers/HandlerTest.kt"),
                graph.testsFor(listOf("src/main/kotlin/pay/Router.kt")).mapTo(HashSet()) { it.path },
            )
            // HandlerTest uses handleUser from its own package without an import and is named after no
            // file, so tier 0 has no edge for it; RouterTest imports pay.handlers.handleUser explicitly.
            assertEquals(
                setOf("src/test/kotlin/pay/RouterTest.kt"),
                graph.testsFor(listOf("src/main/kotlin/pay/handlers/User.kt")).mapTo(HashSet()) { it.path },
            )
        }
        FixtureRepos.materialize(Fixture.TsSmall).use { repo ->
            val graph = graphOf(repo.root)
            assertEquals(
                setOf("test/router.test.ts"),
                graph.testsFor(listOf("src/router.ts")).mapTo(HashSet()) { it.path },
            )
        }
    }
}
